Deploy LPRewardsTBTCSaddle to local/Ropsten network
keep-network/keep-ecdsa pull request #684
Opened 2021-02-09 11:12 UTC by r-czajkowski

This PR deploys the `LPRewardsTBTCSaddle` contract to the local/Ropsten network. It also fixes an issue that the KEEP token dashboard doesn't work because imports the `LPRewardsTBTCSaddle` that doesn't exist in the network.

2021-02-09 18:23 UTC, nkuba requested changes

2021-02-09 18:23 UTC, nkuba commented on solidity/scripts/liquidity-rewards-starter.js
> +const getWrappedTokenContract = async (LPRewardsContract) => {
We're expecting a contract instance here so maybe name it starting with lowercase as we do elsewhere?
```suggestion
const getWrappedTokenContract = async (lpRewardsContract) => {
```

2021-02-09 18:23 UTC, nkuba commented on solidity/scripts/liquidity-rewards-starter.js
> +        wrappedTokenContract: null,
Do we have to define this property? Wouldn't it be enough to do `LP_REWARDS[key].wrappedTokenContract = await getWrappedTokenContract(...`?

2021-02-09 18:23 UTC, nkuba commented on solidity/scripts/liquidity-rewards-starter.js
> +    for (let i = 8; i < 10; i++) {
Could we include this loop in the one above so we won't need to do `for (const values of Object.values(LP_REWARDS))` again?

2021-02-09 18:23 UTC, nkuba commented on solidity/scripts/liquidity-rewards-starter.js
> +    for (const key of Object.keys(LP_REWARDS)) {
Could this be `const value of Object.values(LP_REWARDS)`, so we replace `LP_REWARDS[key]` with `value`?

After we combine loops and do the above maybe we could simplify it to:
```js
for (const value of Object.values(LP_REWARDS)) {
  const wrappedTokenContract = await getWrappedTokenContract(value.contract)
  
  await initLPRewardContract(value.contract, keepToken, lpRewardsOwner, reward)

  for (let i = 8; i < 10; i++) {
    const staker = accounts[i]
    const amount = web3.utils.toWei(`${i * 100}`)

    await mintAndApproveLPReward(wrappedTokenContract, value.contract.address, staker, amount)
  }
}
       
```

2021-02-09 18:23 UTC, nkuba commented on solidity/scripts/liquidity-rewards-starter.js
> +    const LP_REWARDS = {
Maybe we don't need a map? Could it be a simple array? We could also get contracts instances in the loop.

```js
const LPRewardsContracts = [LPRewardsKEEPETH, LPRewardsTBTCETH, LPRewardsKEEPTBTC, LPRewardsTBTCSaddle]

for (const LPRewardsContract of LPRewardsContracts){
  const lpRewardsContract = await LPRewardsContract.deployed()
  ...
}
```

2021-02-10 08:44 UTC, r-czajkowski commented
@nkuba ready for the next round.

2021-02-10 13:12 UTC, nkuba approved these changes

2021-02-10 13:13 UTC, merged