Refactor workflows to add deployment of contracts migrated on Celo
keep-network/keep-ecdsa pull request #823
Opened 2021-06-10 12:04 UTC by michalinacienciala

Workflows have been refactored so that Celo-related artifacts could be
deployed in the chain of automatic execusions triggered by the manual
dispatch of the `Main` workflow in the `ci` project (with `environment`
set to `alfajores`).

Similar changes have been introduced to `keep-core` and `tbtc`
workflows. See:
https://github.com/keep-network/keep-core/pull/2492

2021-07-02 10:47 UTC, nkuba requested changes

2021-07-02 10:47 UTC, nkuba commented on .github/workflows/client.yml
>        - # Temp fix - move cache instead of copying (added below step and
Can we move it to be the very last step (after `Notify CI about completion of the workflow`)?

2021-07-02 10:48 UTC, nkuba commented
@michalinacienciala can we solve the conflicts, please?

2021-07-05 07:58 UTC, nkuba commented
@michalinacienciala we've got some formatting problems.

2021-07-05 13:41 UTC, michalinacienciala commented
> @michalinacienciala we've got some formatting problems.

Fixed in 08bdbe82831b53bd53a2a8c75536aa71bb533cad.

2021-07-06 06:26 UTC, michalinacienciala commented
@nkuba, after merging the change, there would be a need for change in the configuration of required jobs - `client-build-test-publish-ethereum` should become required (instead of `client-build-test-publish`).
We should also consider whether to make celo-related jobs required...

2021-07-06 07:18 UTC, nkuba requested changes

2021-07-06 09:17 UTC, michalinacienciala commented on .github/workflows/contracts.yml
>          run: npx truffle migrate --reset --network $TRUFFLE_NETWORK
The value is read from either `ropsten.env` or `alfajores.env` config file, thanks to execution of `load-env-variables` action few steps before.
In the `run` parameter both notations work, I think - the `$TRUFFLE_NETWORK` and the `${{ env.TRUFFLE_NETWORK }}`.

2021-07-06 09:21 UTC, michalinacienciala commented on .github/workflows/contracts.yml
> +      # `npm ci` isn't run in the root directory.
Fixed, see 5ec358d98f04727795ea5052d229a34957d096ef.

2021-07-06 14:05 UTC, nkuba commented on .github/workflows/contracts.yml
>          run: npx truffle migrate --reset --network $TRUFFLE_NETWORK
I would do `TRUFFLE_NETWORK: ${{ env.TRUFFLE_NETWORK }}` so it's more clear that we set the value.

2021-07-06 14:15 UTC, michalinacienciala commented on .github/workflows/contracts.yml
>          run: npx truffle migrate --reset --network $TRUFFLE_NETWORK
Done, see 4c988762015b84eb02c69bcbd438de975ce89d6e

2021-07-06 14:16 UTC, nkuba approved these changes

2021-07-06 14:27 UTC, merged